### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by panachi-cw** [cloudwalk/infinitepay-woocommerce-plugin#12]
Plugin authentication though JWT credentials:

![Image](https://user-images.githubusercontent.com/104794820/180515407-11f8b6a8-b9e0-4b40-8f1c-c94bb201bfb5.png)

Additional flows:
- Include a link to signup / dashboard credentials request;
- Include a button to validate credentials (request an access_token and register that merchant has validated the credential;

**Comment by malkafly-cw** [comment]
Instead of the "Validar" button for validation, I kept the old Save cta, it will validate and only store the credentials on success or return a warning/error message.

**Comment by bru-carenzi** [comment]
Validated! 

![Captura de Tela 2022-08-26 às 17 37 35](https://user-images.githubusercontent.com/93997860/186987070-f9719788-41f4-41f6-afe3-92e72ffa8ea5.png)
