### ISSUE TITLE
Add from-to setting to map WooCommerce vs Payment statuses

### ISSUE THREAD

**Issue by ricardocicicw** [cloudwalk/infinitepay-woocommerce-plugin#19]
As an User, I want to be able to choose what transaction status will be set after I receive a:
- Approved credit card transaction
- Pending PIX transaction
- Approved PIX transaction

Default values:
- Approved Credit Card Transaction > Processing
- Pending PIX Transaction > Pending Payment
- Approved PIX Transaction > Processing

The user will only be able to choose between default WooCommerce values.

Settings and integrations may be different between clients, and would be better for us to leave it flexible for customer to choose.

Wireframe:

![Image](https://user-images.githubusercontent.com/104794820/180515876-01862d6e-36cc-43e1-960c-241fe7ae0a97.png)

**Comment by bru-carenzi** [comment]
Validated

![Captura de Tela 2022-08-26 às 17 42 32](https://user-images.githubusercontent.com/93997860/186987817-37092d01-05b5-4662-b749-967b22ef94ab.png)
